### PR TITLE
chore: updating legacy-peer-dependencies

### PR DESCRIPTION
**Pull request by grvv**
- Updates webpack v3 to v4
- Updates webpack config
- Updates babel loader and it's presets/plugins/loaders

### CODE REVIEW

**Comment by coolsoftwaretyler** [comment]
@grvv - do we strictly need to update Webpack in order to move off the old legacy peer dependencies?

I was hoping we could do this in stages as listed in the milestone: https://github.com/mobxjs/mobx-devtools/milestone/1

If we can get off the legacy peer dependencies in one small move, then we can upgrade Webpack in its own PR (or multiple PRs if we want to do it version by version)

If Webpack itself is using legacy peer dependencies, then we can focus on the migration (or maybe swap over to Vite).

**Comment by grvv** [comment]
Screenshot 2024-10-15 at 8 21 24 PM

@coolsoftwaretyler 

When you first run npm install, you'll encounter this error

We have two options here: we can either downgrade eslint-loader and stick with Webpack 3 for now, or proceed with upgrading Webpack. I opted for the latter because the upgrade wasn’t too much work, and this will allow us to temporarily maintain compatibility while we address the other peer dependencies. Once those are resolved, we can then decide whether to transition to Vite or another solution. I think keeping this setup temporarily shouldn't cause major issues.

**Comment by coolsoftwaretyler** [comment]
Thanks for the details! I have a slight preference for downgrading the loader in this specific PR. I think the Webpack upgrade is a big enough change that we should handle it separately.

If downgrading eslint-loader allows us to stop using the legacy peer dependencies flag, and all of the current scripts work after that, then we can keep this PR scoped a little more tightly.

If it causes more work in some other direction, then yeah let's move forward with the full upgrade, in which case maybe you and I can find some time to talk it through in a video call since it will take some extra coordination.

**Comment by grvv** [comment]
Downgrading a few dependencies did the trick 😄 (postponing the bundler upgrade for later). Closing this PR, and here’s the link for the [new one](https://github.com/mobxjs/mobx-devtools/pull/122). All the scripts (bootstrap, build, start) are working fine, though with some warnings. I removed the --legacy-peer-deps flag from the bootstrap script, and everything is installing correctly now.

**Pull request closed without merging**
