### PR TITLE
Migrate to Webpack 5, updated linting and libs

### PR DESCRIPTION
**Pull request by grvv**
## Webpack Migration

- Migrated from **Webpack v3** to **v5**, leveraging previous work from the v3 to v4 upgrade.
- Updated all Webpack configurations to be compatible with Webpack 5.
- Removed deprecated plugins and loaders, utilizing Webpack 5's built-in features.

## Dependency Updates

- Updated **Babel** libraries and adjusted `.babelrc` configurations.
- Updated testing libraries, including **Mocha** and **Chai**.
- Fixed linting issues by updating **ESLint** configurations (`.eslintrc`).
- Ran **Prettier** on the codebase (`npx prettier --write .`) to ensure consistent code formatting.

## Future Enhancements

- Plan to experiment with **Rspack** for potential build performance improvements.

### CODE REVIEW

**Comment by grvv** [comment]
Used the code from my previous PR to transition from Webpack v3 to v4 (https://github.com/mobxjs/mobx-devtools/pull/121).

**Comment by coolsoftwaretyler** [comment]
Thanks @grvv! Just got back from a work trip so I'll take a look this weekend but I suspect we'll get things merged pretty soon here.

**Comment by coolsoftwaretyler** [comment]
Looking good! There was an issue with the Electron playground with command `npm run start-playground-electron`, so I've fixed that in 3f596092d6aa752eee70eae87186bff80c1eb3f2. Will check the other commands one more time here.

**Comment by coolsoftwaretyler** [comment]
Everything except e2e tests is passing, and I've checked the built browser extension works in the playground. We've had problems with e2e tests for a while, so I will not block on that. Merging.

Thanks so much, @grvv!

**Pull request merged**
